config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#show'

  resources :posts
  resources :users, only: [:new, :create, :index, :show]
  get "/signup", to: "users#new", as: 'signup'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :users
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts
  has_secure_password
  has_secure_token :confirmation_token
  validates :first_name, 
  format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" },
    presence: true

  validates :last_name,
  format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" },
   presence: true
  validates :email,
   format: { with: /\A[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}\z/i, message: 'email non valide'},
   uniqueness: { case_sensitive: false },
   presence: true


  def admin?
    email == 'estelle.jl.rose@gmail.com'
  end

  def user_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?, :current_user

    def current_user
      if session[:user_id]
        @user = User.find(session[:user_id])
      end
    end
  
    def logged_in?
      !!current_user
    end
  
    def authorized
      redirect_to login_path unless logged_in?
    end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def show; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    posts = Post.all
    if posts.any?
      render :index, locals: { posts: }, status: :ok
    else
      render(json: { message: 'posts not found' }, status: :not_found)
    end
  end
  def show
    post_id = params[:id]
    post = Post.find(post_id)
    if post.present?
      render :show, locals: { post: }, status: :ok
    else
      render(json: { message: 'post not found' }, status: :not_found)
    end
  end
  def edit
    post = Post.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
          session[:user_id] = user.id
          redirect_to user, notice: "Logged in successfully."
        else
          redirect_to login_path, alert: "There was something wrong with your login details."
        end
    end
       
      def destroy
        session[:user_id] = nil
        flash[:notice] = "You have been logged out."
        redirect_to root_path
      end
  end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    users = User.all
    if users.any?
      render :index, locals: { users: }, status: :ok
    else
      render(json: { message: 'users not found' }, status: :not_found)
    end
  end
  def show
    user = User.find(params[:id])
  render :show, locals: { user: }, status: :ok
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to @user
    else
      render :new
    end
  end
  private
  def user_params
     params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/alert_helper.rb
module AlertHelper
    def build_alert_classes(alert_type)
      classes = 'alert alert-dismissable '
      case alert_type.to_sym 
      when :alert, :danger, :error, :validation_errors
          classes += 'alert-danger'
      when :warning, :todo
          classes += 'alert-warning'
      when :notice, :success
          classes += 'alert-success'
      else 
          classes += 'alert-info'
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/show.html.erb
<h1 class>Hello you !</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>C</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'true' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </head>

  <body>

     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="<%= root_path %>">A rails app</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample06" aria-controls="navbarsExample06" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample06">
        <ul class="navbar-nav mr-auto">
       
          <li class="nav-item active">
            <a class="nav-link" href="<%= signup_path %>">Inscription</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="<%= login_path %>">Connexion</a>
          </li>
           <li class="nav-item ">
            <a class="nav-link" href="<%= users_path %>">Auteurs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= posts_path %>">Articles</a>
          </li>
        
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown06" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown06">
              <a class="dropdown-item" href="">Connexion</a>
              <a class="dropdown-item" href=<%= users_path %>>Auteurs</a>
              <a class="dropdown-item" href=<%= posts_path %>>Articles</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-md-0">
          <input class="form-control" type="text" placeholder="Search">
        </form>
      </div>
    </nav>
  <% flash.each do |type, msg| %>
    <%= content_tag :div, msg, class: build_alert_classes(type) %>
  <% end %>
   <div class="container" style="padding-top: 5rem;display: flex; justify-content: center;align-items: center;">
    <%= yield %>
   </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
    <h1 class="pb-3">Ajouter un article</h1>
     <%= form_for( post , remote: true) do |f| %>
       <%=%>
       <% end %>
        <p>
          <a href="<%= posts_path%>" class="btn btn-primary">Revenir aux articles</a>
        </p>
</div>

app/views/posts/index.html.erb
<div class="container">
    <h1 class="pb-3">Posts du blog</h1>
    <%= posts.each do |post| %>
        <h2><%= post.title %></h2>
        <p><%= post.content %></p>
        <p>
          <a href="<%= post_path(post.id)%>" class="btn btn-primary">Lire la suite</a>
        </p>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
    <h1 class="pb-3"><%= post.title %></h1>
        <p><%= post.content %></p>
        <p>
          <a href="<%= posts_path%>" class="btn btn-primary">Revenir aux articles</a>
        </p>
</div>

app/views/users/index.html.erb
<div class="container">
    <h1 class="pb-3">A bunch  of users</h1>
    <div>
        <% users.each do |name| %>
        <p class="center"><%= name.user_name %></p>
        <% end %>
    </div>

</div>

app/views/users/new.html.erb
<div class="container">
    <% if @user.errors.any?%>
        <div class="alert alert-danger">
        <ul>
        <% @user.errors.full_messages.each do | message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
        </div>
    <% end %>
    <h1 class="py-5 text-center">S'inscrire</h1>
        <div class="row">
            <%= form_with(model: @user) do |f| %>
                <div class="card">
                    <div class="card-body">

                        <div class="mb-3">
                        <%= f.label :first_name, 'Prénom', { class: "form-label"} %>
                        <%= f.text_field :first_name, { class: "form-control", placeholder: "Prénom" } %>
                        </div>
                        <div class="mb-3">
                        <%= f.label :last_name, 'Nom' , { class: "form-label"}%>
                        <%= f.text_field :last_name, { class: "form-control", placeholder: "Nom" } %>
                        </div>

                        <div class="mb-3">
                        <%= f.label :email, { class: "form-label"} %>
                        <%= f.text_field :email, { class: "form-control", placeholder: "Email" } %>
                        </div>

                        <div class="mb-3">
                        <%= f.label :password, 'Mot de passe', { class: "form-label"} %>
                        <%= f.password_field :password, { class: "form-control", placeholder: "Mot de passe" } %>
                        </div>
                        <div class="mb-3">
                        <%= f.label :password_confirmation, 'Confirmer le mot de passe', { class: "form-label"} %>
                        <%= f.password_field :password, { class: "form-control", placeholder: "Mot de passe" } %>
                        </div>

                        <%= f.submit "Submit", class: "btn btn-primary" %>

                    </div>
                </div>
            <% end %> 
        </div>
</div>

app/views/users/show.html.erb
<h1>Hello <%= user.user_name %> comment ça va ?</h1>